theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

title: Python-The Tutorial
github:
  repository_url = https://www.sjportfolio.cf/404.html
  

