theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

title: Python-The Tutorial
github:
  repository_url = https://www.sjportfolio.cf/404.html
  Repl_Talk_url = https://repl.it/talk/learn/PYTHON-TUTORIAL/92006
  Lets_play_url = https://python.blip.gq/#run-the-tutorial-here
