theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

title: Python-The Tutorial
github:
  repository_url = https://www.sjportfolio.cf/404.html
  
<a href="https://repl.it/talk/learn/PYTHON-TUTORIAL/92006" class="btn btn-github"><span class="icon"></span>Repl Talk</a>
<a href="{https://python.blip.gq/#run-the-tutorial-here" class="btn btn-github"><span class="icon"></span>Run the Tutorial</a>

